---
# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Upload Python Package
on:
  release:
    types: [published]
  # push:
  #   tags: ['v[0-9]+.[0-9]+.[0-9]+']
env:
  PACKAGE_NAME: python-sonnetsuiteshelper
  OWNER: Alan-Manning
permissions:
  contents: read
jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          python -m pip install build
          python -m build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
  pypi-publish:
    runs-on: ubuntu-latest
    needs: [release-build]
    permissions:
      id-token: write
    environment:
      name: pypi-publish
      url: https://pypi.org/project/sonnetsuiteshelper/
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
#
# ---
# name: Publish to PyPI
# on:
#   release:
#     types: [created]
# jobs:
#   publish-to-pypi:
#     name: >-
#       Publish Python distribution to PyPI
#     if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
#     runs-on: ubuntu-latest
#     environment:
#       name: pypi
#       url: https://pypi.org/p/sonnetsuiteshelper
#     permissions:
#       id-token: write  # IMPORTANT: mandatory for trusted publishing
#     steps:
#       - name: Download all the dists
#         uses: actions/download-artifact@v4
#         with:
#           name: python-package-distributions
#           path: dist/
#       - name: Publish distribution to PyPI
#         uses: pypa/gh-action-pypi-publish@release/v1
  # publish-to-testpypi:
  #   name: Publish Python distribution to TestPyPI
  #   needs:
  #   - build
  #   runs-on: ubuntu-latest
  #
  #   environment:
  #     name: testpypi
  #     url: https://test.pypi.org/p/sonnetsuiteshelper
  #
  #   permissions:
  #     id-token: write  # IMPORTANT: mandatory for trusted publishing
  #
  #   steps:
  #   - name: Download all the dists
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: python-package-distributions
  #       path: dist/
  #   - name: Publish distribution to TestPyPI
  #     uses: pypa/gh-action-pypi-publish@release/v1
  #     with:
  #       repository-url: https://test.pypi.org/legacy/
